"""The ~300-word high-frequency structural core of Talmudic Aramaic.

``FUNCTION_WORDS`` maps the plain (nikud-stripped, normalized) form of each
function word to a short English gloss. These are curated dictionary
headwords — Aramaic/Mishnaic-Hebrew particles, conjunctions, demonstratives,
interrogatives, suffixed prepositions, verbs of saying/teaching/asking, and
the very high-frequency legal outcome terms — NOT generated passages, so
hard rule 1 does not apply to this list.

A token is "structural" if it is in this list, possibly behind a single
clitic vav/dalet/shin prefix (see :func:`is_function`).
"""

from __future__ import annotations

from .normalize import VARIANT_MAP

FUNCTION_WORDS: dict[str, str] = {
    # ---- copula / existence -------------------------------------------------
    "הוא": "he / it is",
    "היא": "she / it is (f.)",
    "הוי": "is / becomes",
    "הוה": "was",
    "הויא": "was (f.)",
    "הוו": "were",
    "ליהוי": "let it be",
    "תיהוי": "let it be (f.)",
    "נינהו": "they are",
    "ניהו": "it is (emphatic)",
    "אית": "there is",
    "לית": "there is not",
    "איכא": "there is / there are",
    "ליכא": "there is not",
    "איתא": "it is so / it exists",
    "ליתא": "it is not so",
    "איתיה": "he/it is present",
    "ליתיה": "he/it is absent",
    "יש": "there is",
    "ישנו": "it exists",
    # ---- negation -----------------------------------------------------------
    "לא": "no / not",
    "אין": "there is not / no",
    "לאו": "not / is it not",
    "אל": "do not",
    "אינו": "he/it is not",
    "אינה": "she/it is not",
    "אינן": "they are not",
    "ולא": "and not",
    "דלא": "that not",
    "שלא": "that not / without",
    "בלא": "without",
    # ---- interrogatives -----------------------------------------------------
    "מאי": "what?",
    "מי": "who? / is it that...?",
    "מה": "what",
    "מהו": "what is it? (what is the law?)",
    "מאן": "who?",
    "מנא": "from where?",
    "מנלן": "from where do we (know) it?",
    "מנין": "from where (is it derived)?",
    "מניין": "from where (is it derived)?",
    "היכי": "how?",
    "היכא": "where?",
    "מהיכא": "from where?",
    "אמאי": "why?",
    "למה": "why?",
    "למאי": "for what?",
    "כמה": "how much / how many",
    "אימת": "when?",
    "אימתי": "when?",
    "הי": "which?",
    "איזה": "which?",
    "איזו": "which? (f.)",
    "וכי": "and is it that...?",
    "אטו": "is it that...? (rhetorical)",
    "מכדי": "now, since (introducing a premise)",
    "כלום": "anything / is there any...?",
    # ---- demonstratives & 3rd-person pronouns -------------------------------
    "הא": "this / behold",
    "האי": "this (m.)",
    "ההוא": "that (m.) / a certain",
    "ההיא": "that (f.) / a certain",
    "הני": "these",
    "הנהו": "those",
    "הנך": "those (other)",
    "הך": "that one",
    "אידך": "the other",
    "אידי": "this one",
    "זה": "this (m.)",
    "זו": "this (f.)",
    "זהו": "this is",
    "אלו": "these",
    "הללו": "these",
    "ההם": "those (m.)",
    "ההן": "those (f.)",
    "האידנא": "nowadays",
    "איהו": "he",
    "איהי": "she",
    "אינהו": "they",
    "הם": "they (m.)",
    "הן": "they (f.) / yes",
    # ---- 1st/2nd-person pronouns & possessives ------------------------------
    "אנא": "I",
    "אנן": "we",
    "אנו": "we",
    "את": "you / (object marker)",
    "אתה": "you (m.)",
    "אתם": "you (pl.)",
    "אתון": "you (pl., Aramaic)",
    "דידי": "mine",
    "דידך": "yours",
    "דידיה": "his",
    "דידה": "hers",
    "דידן": "ours",
    "דידהו": "theirs",
    "של": "of",
    "שלו": "his",
    "שלה": "hers",
    "שלהם": "theirs",
    # ---- conditionals / conjunctions / discourse particles -------------------
    "אי": "if",
    "אם": "if",
    "אילו": "if (hypothetical)",
    "אילימא": "if you say",
    "אלמלא": "were it not for",
    "אלא": "rather / but",
    "ואלא": "but rather",
    "או": "or",
    "אף": "also / even",
    "אפילו": "even",
    "ואפילו": "and even",
    "נמי": "also",
    "וכן": "and likewise",
    "כן": "so / thus",
    "הכי": "thus / so",
    "והכי": "and thus",
    "כי": "when / for / like",
    "דכי": "for when",
    "הואיל": "since",
    "כיון": "once / since",
    "וכיון": "and since",
    "מכלל": "it follows (by implication)",
    "אדרבה": "on the contrary",
    "איפכא": "the opposite",
    "מיהו": "however",
    "מיהא": "at any rate",
    "מיהת": "at any rate",
    "ברם": "however",
    "אבל": "but",
    "הלכך": "therefore",
    "לפיכך": "therefore",
    "משום": "because of",
    "ומשום": "and because of",
    "דילמא": "perhaps",
    "שמא": "perhaps / lest",
    "ודאי": "certainly",
    "דוקא": "specifically / precisely",
    "גם": "also",
    "רק": "only",
    "אך": "but / only",
    "כדי": "in order to / the amount of",
    "בכדי": "for nothing / in vain",
    "היינו": "that is",
    "דהיינו": "that is to say",
    "כלומר": "that is to say",
    "ממילא": "automatically / by itself",
    "אגב": "by the way of / incidentally",
    "תו": "further / anymore",
    "ותו": "and furthermore",
    # ---- verbs of saying ----------------------------------------------------
    "אמר": "said",
    "אמרו": "they said",
    "אמרה": "she said",
    "אמרי": "they say / I say",
    "אמרת": "you said",
    "אמרינן": "we say",
    "אומר": "says",
    "אומרים": "they say",
    "אימא": "say! / I could say",
    "אימר": "say / one could say",
    "נימא": "let us say",
    "לימא": "shall we say",
    "קאמר": "he is saying",
    "קאמרי": "they are saying",
    "קאמרת": "you are saying",
    "דקאמר": "that he says",
    "דאמר": "who said / for he said",
    "דאמרי": "who say",
    "דאמרינן": "as we say",
    "ואמר": "and he said",
    "ואמרי": "and they say",
    "למימר": "to say",
    "למימרא": "is this to say...?",
    "לומר": "to say",
    "וליטעמיך": "and according to your reasoning",
    # ---- citation formulas (Scripture & tannaitic sources) -------------------
    "שנאמר": "as it is stated (Scripture)",
    "נאמר": "it is stated",
    "כתיב": "it is written",
    "דכתיב": "as it is written",
    "וכתיב": "and it is written",
    "כדכתיב": "as it is written",
    "קרא": "the verse",
    "תנא": "(a) tanna taught",
    "תנן": "we learned (in the Mishnah)",
    "דתנן": "as we learned (in the Mishnah)",
    "והתנן": "but didn't we learn (in the Mishnah)",
    "תניא": "it is taught (in a baraita)",
    "דתניא": "as it is taught (in a baraita)",
    "והתניא": "but isn't it taught (in a baraita)",
    "תנו": "(the Sages) taught",
    "קתני": "it teaches",
    "דקתני": "that it teaches",
    "מתניתין": "our Mishnah",
    "ברייתא": "baraita (external teaching)",
    "איתמר": "it was stated (amoraic)",
    "אתמר": "it was stated (amoraic)",
    # ---- asking / objecting / resolving --------------------------------------
    "בעי": "asks / requires",
    "בעא": "he asked",
    "בעיא": "question / requires (f.)",
    "איבעיא": "a dilemma was raised",
    "מיבעיא": "is it necessary (to say)?",
    "מיבעי": "it is needed",
    "שאל": "asked",
    "פריך": "objects",
    "קשיא": "it is difficult",
    "קשה": "difficult",
    "רמי": "raises a contradiction",
    "ורמינהו": "and contrast (these sources)",
    "רמינהו": "contrast (these sources)",
    "מיתיבי": "they object (from a baraita)",
    "איתיביה": "he objected to him",
    "מותיב": "raises an objection",
    "תיובתא": "a refutation",
    "תיקו": "let it stand (unresolved)",
    "שמע": "hear / infer",
    "שמעת": "you heard",
    "שמעינן": "we infer",
    "משמע": "it implies",
    "מינה": "from it (f.)",
    "נפקא": "derives / goes out (f.)",
    # ---- holding / reasoning ------------------------------------------------
    "סבר": "holds / reasoned",
    "סברי": "they hold",
    "סברוה": "they assumed",
    "קסבר": "he holds",
    "דסבר": "who holds",
    "סבירא": "is of the opinion",
    "סלקא": "arises",
    "דעתך": "your mind (in: it might enter your mind)",
    "דעתא": "mind / intention",
    "אדעתא": "with the intention of",
    "מסתברא": "it stands to reason",
    "פשיטא": "it is obvious",
    "עסקינן": "we are dealing (with)",
    "מוקמינן": "we establish (the case)",
    "אוקימנא": "we established (the case)",
    "תרגמה": "he explained it",
    "קמשמע": "it teaches us (in: ka mashma lan)",
    "צריך": "needs / must",
    "צריכא": "it is necessary",
    "צריכי": "they are necessary",
    "איצטריך": "it was necessary",
    "ניחא": "it is fine / settled",
    "שפיר": "well / properly",
    "בשלמא": "granted",
    "חזי": "see / fit",
    "חזינן": "we see",
    "דמי": "is similar / it is like",
    "דמיא": "is similar (f.)",
    "תיפוק": "derive it (in: tipuk lei)",
    "איריא": "it applies (in: lo iry'a)",
    "שנא": "different (in: mai shna)",
    # ---- motion & common light verbs -----------------------------------------
    "אתא": "came",
    "אתי": "comes",
    "אתו": "they came",
    "אזל": "went",
    "אזיל": "goes",
    "אזלי": "they go",
    "נפק": "went out",
    "עייל": "entered",
    "קם": "arose",
    "קאי": "stands / refers to",
    "יתיב": "sat",
    "תא": "come (in: ta shma — come and hear)",
    "זיל": "go!",
    "יהיב": "gave",
    "שקיל": "takes",
    "עביד": "does / did",
    "עבד": "did",
    "עבדינן": "we do",
    "נקט": "took / held",
    "נקיט": "holds",
    # ---- prepositions & suffixed prepositions --------------------------------
    "מן": "from",
    "על": "on / about",
    "עליו": "on him",
    "עליה": "on him/it (Aram.) / on her (Heb.)",
    "עלה": "on it (f.)",
    "עילויה": "upon him",
    "עד": "until",
    "עם": "with",
    "אצל": "by / at",
    "גבי": "regarding / by",
    "לגבי": "with respect to",
    "קמיה": "before him",
    "קמי": "before",
    "מקמי": "from before",
    "בתר": "after",
    "בתריה": "after him",
    "מיניה": "from him/it",
    "מינייהו": "from them",
    "ממנו": "from him/it",
    "ביה": "in him/it",
    "בה": "in her/it",
    "בהו": "in them",
    "בו": "in him/it (Heb.)",
    "בהם": "in them (m.)",
    "בהן": "in them (f.)",
    "ליה": "to him",
    "לה": "to her",
    "להו": "to them",
    "לי": "to me",
    "לך": "to you",
    "לן": "to us",
    "לכו": "to you (pl.)",
    "לנו": "to us (Heb.)",
    "להם": "to them (Heb.)",
    "לו": "to him (Heb.)",
    "ממאי": "from what (do you derive)?",
    "מכאן": "from here",
    "מהכא": "from here (Aram.)",
    "מהתם": "from there (Aram.)",
    "בהדי": "together with",
    "בהדיה": "with him",
    "בהדייהו": "with them",
    "אהדדי": "with one another",
    "כוותיה": "in accordance with him",
    "תחת": "under / instead of",
    "תחתיו": "in his place",
    "כנגד": "opposite / corresponding to",
    "כנגדו": "opposite him",
    "לפני": "before",
    "לפניו": "before him",
    "בפני": "in the presence of",
    "בפניו": "in his presence",
    "מפני": "because of",
    # ---- quantifiers & numerals ----------------------------------------------
    "כל": "all / every",
    "הכל": "everyone / everything",
    "כולה": "all of it (f.)",
    "כוליה": "all of it (m.)",
    "כולהו": "all of them",
    "כולם": "all of them (Heb.)",
    "מידי": "anything / something",
    "טובא": "much / many",
    "פורתא": "a little",
    "רובא": "the majority",
    "מקצת": "part of",
    "חד": "one (m.)",
    "חדא": "one (f.)",
    "אחד": "one (m., Heb.)",
    "אחת": "one (f., Heb.)",
    "תרי": "two (m.)",
    "תרתי": "two (f.)",
    "שנים": "two (Heb.)",
    "שתי": "two (f. construct)",
    "תלת": "three",
    "תלתא": "three (m.)",
    "שלשה": "three (Heb.)",
    "ארבע": "four",
    "ארבעה": "four (m.)",
    "חמשה": "five",
    "עשרה": "ten",
    # ---- time & place adverbs -------------------------------------------------
    "הכא": "here",
    "התם": "there",
    "השתא": "now",
    "מעיקרא": "originally / at first",
    "לבסוף": "in the end",
    "אכתי": "still / yet",
    "שוב": "again / furthermore",
    "כבר": "already",
    "לעולם": "actually / forever",
    "עדיין": "still",
    "היום": "today",
    "למחר": "tomorrow",
    "לאלתר": "immediately",
    "מיד": "immediately",
    "לעיל": "above",
    "לקמן": "below / later",
    "היכן": "where (Heb.)",
    "כאן": "here (Heb.)",
    "שם": "there (Heb.) / name",
    "אחר": "after / another",
    "אחרי": "after",
    "קודם": "before (temporal)",
    "בתחילה": "at first",
    "בסוף": "at the end",
    "זימנין": "sometimes / times",
    "זימנא": "time / occasion",
    "פעמים": "sometimes / times",
    "פעם": "time / occasion",
    "הדר": "returned / retracted",
    # ---- legal outcome terms (very high frequency core) -----------------------
    "חייב": "liable / obligated",
    "חייבת": "liable (f.)",
    "פטור": "exempt",
    "פטורה": "exempt (f.)",
    "אסור": "forbidden",
    "אסורה": "forbidden (f.)",
    "מותר": "permitted",
    "מותרת": "permitted (f.)",
    "כשר": "valid / fit",
    "כשרה": "valid (f.)",
    "פסול": "invalid / unfit",
    "פסולה": "invalid (f.)",
    "טמא": "ritually impure",
    "טהור": "ritually pure",
    "זכאי": "entitled / acquitted",
    "קנה": "acquired",
    "קני": "acquires",
    "קנו": "they acquired",
    "זכין": "one may act to effect a benefit (for someone)",
    "זכה": "acquired / gained title",
    "זוכה": "acquires / gains",
    "חבין": "one may act to a person's detriment",
    "מהני": "is effective",
    "מהניא": "is effective (f.)",
    "הלכה": "the halakha (law)",
    "הלכתא": "the halakha (Aram.)",
    "דינא": "the law / judgment",
    "דין": "law / judgment",
    "טעמא": "the reason",
    "טעם": "reason",
    # ---- titles & structural nouns --------------------------------------------
    "רבי": "Rabbi",
    "רב": "Rav",
    "רבנן": "the Sages",
    "מר": "Master / one (authority)",
    "בן": "son of",
    "בר": "son of (Aram.)",
    "בני": "sons of / members of",
    "בית": "house of / school of",
    "דבי": "of the school of",
    "דברי": "the words of",
    "דבר": "thing / matter",
    "מילי": "words / matters",
    "מילתא": "matter / word",
    "מעשה": "incident / deed",
    "גוונא": "manner (in: kehai gavna — in this manner)",
}

#: Single-letter clitic prefixes that may sit in front of a function word
#: (vav "and", dalet "that/of", shin "that") without changing its structural
#: status. Bet/lamed/kaf/mem prefixes are NOT auto-stripped here because they
#: frequently create content readings; high-frequency prefixed forms are
#: instead listed explicitly above.
CLITIC_PREFIXES: str = "ודש"


def is_function(token: str) -> bool:
    """True if ``token`` (plain form) is part of the structural core.

    A token counts as a function word if, after applying the orthographic
    variant map, it appears in ``FUNCTION_WORDS`` directly or behind a single
    vav/dalet/shin clitic prefix (e.g. ``ומאי`` "and what?").
    """
    t = VARIANT_MAP.get(token, token)
    if t in FUNCTION_WORDS:
        return True
    if len(t) > 2 and t[0] in CLITIC_PREFIXES:
        rest = VARIANT_MAP.get(t[1:], t[1:])
        if rest in FUNCTION_WORDS:
            return True
    return False


def gloss(token: str) -> str | None:
    """English gloss for a function word (or ``None`` if not one)."""
    t = VARIANT_MAP.get(token, token)
    if t in FUNCTION_WORDS:
        return FUNCTION_WORDS[t]
    if len(t) > 2 and t[0] in CLITIC_PREFIXES:
        rest = VARIANT_MAP.get(t[1:], t[1:])
        if rest in FUNCTION_WORDS:
            prefix_gloss = {"ו": "and", "ד": "that/of", "ש": "that"}[t[0]]
            return f"{prefix_gloss} + {FUNCTION_WORDS[rest]}"
    return None
